dist: xenial
language: java
sudo: false
install: true
addons:
  sonarcloud:
    organization: $SONAR_ORGANIZATION
    token:
      secure: $SONAR_TOKEN
jdk:
  - openjdk11
before_install:
  - chmod +x mvnw
script:
  - mvn clean package sonar:sonar -P sonar
cache:
  directories:
    - $HOME/.m2
    - $HOME/.sonar/cache